In [1]:
import kaggle
import os
from kaggle.api.kaggle_api_extended import KaggleApi

In [5]:
# 设置 Kaggle API 密钥的路径
os.environ['KAGGLE_CONFIG_DIR'] = os.path.expanduser('~/.kaggle')

In [6]:
# 创建 Kaggle API 实例
api = KaggleApi()
api.authenticate()

In [7]:
# kaggle datasets download ankitbansal06/retail-orders -f orders.csv
# 下载数据集
dataset = 'ankitbansal06/retail-orders'
filename = 'orders.csv'

# 下载数据集文件到当前工作目录
api.dataset_download_file(dataset, filename, path='.')

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders

True

In [50]:
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall() #extract file
zip_ref.close()

In [10]:
#read data from the file 
import pandas as pd
df = pd.read_csv('orders.csv', na_values=['Not Available', 'unknown'])
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [3]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [45]:
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [11]:
# df.rename(columns={'Order Id':'order_id','Order Date':'order_date','Ship Mode': 'ship_mode','Segment':'segment','Country':'country','City':'city',
#           'State':'state', 'Postal Code':'zip_code', 'Region':'region', 'Category':'category', 'Sub Category':'sub_category',
#           'Product Id':'product_id', 'cost price':'cost_price', 'List Price':'list_price', 'Quantity':'quantity',
#           'Discount Percent':'Discount_percent'}, inplace=True)
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [12]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [13]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [14]:
# Calculate the discount, sales, profits
df['discount'] = df['list_price'] * df['discount_percent'] * 0.01
df['sale_price'] = df['list_price'] - df['discount']
df['profit'] = df['sale_price'] - df['cost_price']
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [15]:
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [16]:
# convert the order_date format into date
df['order_date'] = pd.to_datetime(df['order_date'], format='%Y-%m-%d')
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [17]:
# delete list_price, discount_percent
df.drop(columns=['list_price', 'discount_percent'], inplace=True)
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'quantity', 'discount', 'sale_price',
       'profit'],
      dtype='object')

In [19]:
import sqlalchemy as sa
# pip install pymysql 
engine = sa.create_engine('mysql+pymysql://root:ifeng%408276@localhost:3306/news', echo=True)
conn = engine.connect()

2024-05-16 15:57:30,957 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2024-05-16 15:57:30,957 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-05-16 15:57:30,960 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2024-05-16 15:57:30,961 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-05-16 15:57:30,962 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2024-05-16 15:57:30,962 INFO sqlalchemy.engine.Engine [raw sql] {}

In [20]:
df.to_sql('orders', conn, index=False, if_exists='replace')

2024-05-16 15:59:50,590 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-05-16 15:59:50,596 INFO sqlalchemy.engine.Engine DESCRIBE `news`.`orders`
2024-05-16 15:59:50,596 INFO sqlalchemy.engine.Engine [raw sql] {}
2024-05-16 15:59:50,605 INFO sqlalchemy.engine.Engine
CREATE TABLE orders (
	order_id BIGINT,
	order_date DATETIME,
	ship_mode TEXT,
	segment TEXT,
	country TEXT,
	city TEXT,
	state TEXT,
	postal_code BIGINT,
	region TEXT,
	category TEXT,
	sub_category TEXT,
	product_id TEXT,
	cost_price BIGINT,
	quantity BIGINT,
	discount FLOAT(53),
	sale_price FLOAT(53),
	profit FLOAT(53)
)


2024-05-16 15:59:50,606 INFO sqlalchemy.engine.Engine [no key 0.00079s] {}
2024-05-16 15:59:50,743 INFO sqlalchemy.engine.Engine INSERT INTO orders (order_id, order_date, ship_mode, segment, country, city, state, postal_code, region, category, sub_category, product_id, cost_price, quantity, discount, sale_price, profit) VALUES (%(order_id)s, %(order_date)s, %(ship_mode)s, %(segment)s, %(country)s, %(city)s, %(state)s, %(postal_code)s, %(region)s, %(category)s, %(sub_category)s, %(product_id)s, %(cost_price)s, %(quantity)s, %(discount)s, %(sale_price)s, %(profit)s)
2024-05-16 15:59:50,744 INFO sqlalchemy.engine.Engine [generated in 0.08593s] [{'order_id': 1, 'order_date': datetime.datetime(2023, 3, 1, 0, 0), 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Henderson', 'state': 'Kentucky', 'postal_code': 42420, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Bookcases', 'product_id': 'FUR-BO-10001798', 'cost_price': 240, 'quantity': 2, 'discount': 5.2, 'sale_price': 254.8, 'profit': 14.800000000000011}, {'order_id': 2, 'order_date': datetime.datetime(2023, 8, 15, 0, 0), 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Henderson', 'state': 'Kentucky', 'postal_code': 42420, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Chairs', 'product_id': 'FUR-CH-10000454', 'cost_price': 600, 'quantity': 3, 'discount': 21.900000000000002, 'sale_price': 708.1, 'profit': 108.10000000000002}, {'order_id': 3, 'order_date': datetime.datetime(2023, 1, 10, 0, 0), 'ship_mode': 'Second Class', 'segment': 'Corporate', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90036, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Labels', 'product_id': 'OFF-LA-10000240', 'cost_price': 10, 'quantity': 2, 'discount': 0.5, 'sale_price': 9.5, 'profit': -0.5}, {'order_id': 4, 'order_date': datetime.datetime(2022, 6, 18, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Fort Lauderdale', 'state': 'Florida', 'postal_code': 33311, 'region': 'South', 'category': 'Furniture', 'sub_category': 'Tables', 'product_id': 'FUR-TA-10000577', 'cost_price': 780, 'quantity': 5, 'discount': 19.2, 'sale_price': 940.8, 'profit': 160.79999999999995}, {'order_id': 5, 'order_date': datetime.datetime(2022, 7, 13, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Fort Lauderdale', 'state': 'Florida', 'postal_code': 33311, 'region': 'South', 'category': 'Office Supplies', 'sub_category': 'Storage', 'product_id': 'OFF-ST-10000760', 'cost_price': 20, 'quantity': 2, 'discount': 1.0, 'sale_price': 19.0, 'profit': -1.0}, {'order_id': 6, 'order_date': datetime.datetime(2022, 3, 13, 0, 0), 'ship_mode': None, 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Furniture', 'sub_category': 'Furnishings', 'product_id': 'FUR-FU-10001487', 'cost_price': 50, 'quantity': 7, 'discount': 1.5, 'sale_price': 48.5, 'profit': -1.5}, {'order_id': 7, 'order_date': datetime.datetime(2022, 12, 28, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Art', 'product_id': 'OFF-AR-10002833', 'cost_price': 10, 'quantity': 4, 'discount': 0.3, 'sale_price': 9.7, 'profit': -0.3000000000000007}, {'order_id': 8, 'order_date': datetime.datetime(2022, 1, 25, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Los Angeles', 'state': 'California', 'postal_code': 90032, 'region': 'West', 'category': 'Technology', 'sub_category': 'Phones', 'product_id': 'TEC-PH-10002275', 'cost_price': 860, 'quantity': 6, 'discount': 45.5, 'sale_price': 864.5, 'profit': 4.5}  ... displaying 10 of 9994 total bound parameter sets ...  {'order_id': 9993, 'order_date': datetime.datetime(2022, 11, 19, 0, 0), 'ship_mode': 'Standard Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Costa Mesa', 'state': 'California', 'postal_code': 92627, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Paper', 'product_id': 'OFF-PA-10004041', 'cost_price': 30, 'quantity': 4, 'discount': 0.9, 'sale_price': 29.1, 'profit': -0.8999999999999986}, {'order_id': 9994, 'order_date': datetime.datetime(2022, 7, 17, 0, 0), 'ship_mode': 'Second Class', 'segment': 'Consumer', 'country': 'United States', 'city': 'Westminster', 'state': 'California', 'postal_code': 92683, 'region': 'West', 'category': 'Office Supplies', 'sub_category': 'Appliances', 'product_id': 'OFF-AP-10002684', 'cost_price': 210, 'quantity': 2, 'discount': 7.2, 'sale_price': 232.8, 'profit': 22.80000000000001}]
2024-05-16 15:59:51,278 INFO sqlalchemy.engine.Engine COMMIT

9994